import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { beginJevCall, completeJevCall, recordJevGameOutcome, startJevSession, recordJevSessionEvent } from "../src/server/jev-audit";
import type { Observation } from "../src/game/decisions";
import type { DecisionMotionEvidence } from "../src/game/decision-freshness";
import { POST as recordOutcome } from "../src/app/api/decision/outcome/route";

test("a live run keeps exact calls, outcomes, latency, tokens and a priced summary", async (t) => {
  const auditRoot = await mkdtemp(join(tmpdir(), "living-matter-audit-test-"));
  t.after(async () => { assert.equal(dirname(auditRoot), resolve(tmpdir())); await rm(auditRoot, { recursive: true, force: true }); });
  const prior = process.env.JEV_SESSION_DIR;
  process.env.JEV_SESSION_DIR = auditRoot;
  t.after(() => { if (prior === undefined) delete process.env.JEV_SESSION_DIR; else process.env.JEV_SESSION_DIR = prior; });
  const sessionId = randomUUID();
  await startJevSession(sessionId);
  const jevRequest = { model: "jev-1.13.0", state: { player_now: { support: "permanent ground" } }, questions: { action_needed: { type: "noul", instructions: "Act?", criteria: { true: "yes", false: "no" } } } };
  const context = { sessionId, candidates: [{ id: "example" }] };
  const call = await beginJevCall(sessionId, jevRequest, context);
  const response = { model: "jev-1.13.0", answers: { action_needed: { type: "noul", noul: 0.73 } }, usage: { input_tokens: 1403, output_tokens: 73 }, request_id: "provider-example", evaluation_time_ms: 143.4 };
  await completeJevCall(call, { providerRoundTripMs: 180, response, decision: { candidateId: "example" } });
  await recordJevGameOutcome(sessionId, call.callId, { status: "applied", reason: "form_created", browserRoundTripMs: 205 });
  const saved = async (name: string) => JSON.parse(await readFile(join(call.directory, name), "utf8"));
  assert.deepEqual(await saved("jev-request.json"), jevRequest);
  assert.deepEqual(await saved("game-context.json"), context);
  assert.deepEqual(await saved("jev-response.json"), response);
  const audit = await saved("audit.json");
  assert.equal(audit.timing.provider_round_trip_ms, 180);
  assert.equal(audit.timing.model_evaluation_ms, 143.4);
  assert.equal(audit.tokens.input, 1403);
  assert.equal(audit.cost.estimated_usd, 0.000058926);
  const summaryPath = join(auditRoot, sessionId, "summary.json");
  let summary = JSON.parse(await readFile(summaryPath, "utf8"));
  assert.equal(summary.successful_calls, 1);
  assert.equal(summary.total_input_tokens, 1403);
  assert.equal(summary.cost.estimated_total_usd, 0.000058926);
  assert.equal(summary.confirmed_game_outcomes.applied, 1);
  const failed = await beginJevCall(sessionId, jevRequest, context);
  await completeJevCall(failed, { providerRoundTripMs: 1600, error: { name: "APITimeoutError", status: null } });
  summary = JSON.parse(await readFile(summaryPath, "utf8"));
  assert.equal(summary.failed_calls, 1);
  const before: Observation = { time: 1, position: [0,1,-25], velocity: [0,0,0], gaze: [1,0,0], grounded: true, activeStructure: "reach" };
  const freshness: DecisionMotionEvidence = { before, after: { ...before, time: 1.3, velocity: [-4,0,0], gaze: [-1,0,0] } };
  const auditEnvironment = ["NODE_ENV", "NEXT_PUBLIC_DECISION_BACKEND", "NEXT_PUBLIC_JEV_SESSION_AUDIT"];
  const previousEnvironment = Object.fromEntries(auditEnvironment.map(key => [key, process.env[key]]));
  Object.assign(process.env, { NODE_ENV: "development", NEXT_PUBLIC_DECISION_BACKEND: "jev", NEXT_PUBLIC_JEV_SESSION_AUDIT: "1" });
  t.after(() => { for (const key of auditEnvironment) { if (previousEnvironment[key] === undefined) delete process.env[key]; else process.env[key] = previousEnvironment[key]; } });
  const outcome = { sessionId, auditId: failed.callId, status: "discarded", reason: "behavior_changed", freshness };
  const postOutcome = (body: unknown) => recordOutcome(new Request("http://localhost/api/decision/outcome", {
    method: "POST", headers: { origin: "http://localhost", "content-type": "application/json" }, body: JSON.stringify(body),
  }));
  assert.equal((await postOutcome(outcome)).status, 200);
  assert.equal((await postOutcome({ ...outcome, freshness: { after: { ...freshness.after, gaze: "look right" } } })).status, 400);
  assert.deepEqual(JSON.parse(await readFile(join(failed.directory, "game-outcome.json"), "utf8")).freshness, freshness);
  assert.equal("freshness" in await saved("jev-request.json"), false);
  assert.equal(summary.cost.estimated_total_usd, null);
  assert.equal(summary.cost.known_estimated_usd, 0.000058926);
  assert.equal(summary.cost.unknown_cost_calls, 1);
  await recordJevSessionEvent(sessionId, { event: "started", simulationTime: 0, recoveries: 0 });
  await recordJevSessionEvent(sessionId, { event: "paused", simulationTime: 20, recoveries: 1 });
  await recordJevSessionEvent(sessionId, { event: "resumed", simulationTime: 20, recoveries: 1 });
  await recordJevSessionEvent(sessionId, { event: "completed", simulationTime: 263.5, recoveries: 1 });
  summary = JSON.parse(await readFile(summaryPath, "utf8"));
  assert.equal(summary.simulation_seconds, 263.5);
  assert.equal(summary.recoveries, 1);
  assert.ok(summary.completed_at);
  assert.ok(summary.playing_wall_seconds >= 0);
});
